name: SchematicaDiscord
api-version: "1.17"
depend: [WorldEdit]
version: "2.0"
description: Save and download schematicas with Discord
author: phonis
main: phonis.SchematicaDownload.SchematicaDownload
commands:
  pschem:
    description: Base command
